// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ7G3BQmwI6koeECdtn5Wl21BceZk_oyQ',
    appId: '1:346606981660:web:455544c2a46ec6152fc5d9',
    messagingSenderId: '346606981660',
    projectId: 'primevideoapp-43bf6',
    authDomain: 'primevideoapp-43bf6.firebaseapp.com',
    storageBucket: 'primevideoapp-43bf6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt2kWDmwynM9rdN6tuvGaEJyvgERjm5bQ',
    appId: '1:346606981660:android:200f87933ac5b8d02fc5d9',
    messagingSenderId: '346606981660',
    projectId: 'primevideoapp-43bf6',
    storageBucket: 'primevideoapp-43bf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0KoOQEiQixmNx7PJfO6hjhuXhxxvYCds',
    appId: '1:346606981660:ios:ceb6dbea2605e8d82fc5d9',
    messagingSenderId: '346606981660',
    projectId: 'primevideoapp-43bf6',
    storageBucket: 'primevideoapp-43bf6.appspot.com',
    androidClientId: '346606981660-150eiiccap50sdco81aaj0av5lgn59us.apps.googleusercontent.com',
    iosClientId: '346606981660-rcf3siicukjvl2nlqtafb26ufs6mumc5.apps.googleusercontent.com',
    iosBundleId: 'com.divinetechs.dtliveapp',
  );
}
