name: pod_player
description: Vimeo and youtube player for flutter, Pod player provides customizable video player controls that support android, ios and web.
homepage: https://github.com/newtaDev/pod_player
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  # services
  video_player: ^2.7.0
  http: ^0.13.6  
  get: ^4.6.5  
  wakelock: ^0.6.2 
  universal_html: ^2.2.3 
  youtube_explode_dart: ^1.12.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0